version: '2'
services:
  schoolmanagement-mysql:
    image: mysql:8.0.20
    volumes:
        - school_management_data:/var/lib/mysql/
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=schoolmanagement
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
volumes:
  school_management_data: